### PR TITLE
Support build hg38 for the extraction of copy number features

### LINKED ISSUE #3: hg38 support
Hi, 

It looks like hg19 chromosome lengths are hardcoded in this package. Would it be possible to add support for hg38? 

Thanks,
Will

### PR DESCRIPTION
**Pull request by lbeltrame**
Two new datasets have been added, `gap_hg38` and `hg38.chrom.sizes`.
They were made as follows:

### `hg38.chrom.sizes`:

```
mysql --user=genome \
    --host=genome-mysql.cse.ucsc.edu \
    -A -e "select chrom, size from hg38.chromInfo" > hg38.chrom sizes
```

Alternative contigs were then removed manually and the data loaded in R, and saved as `hg38.chrom.sizes.rda`.

### `hg38_gap`:

This one is a little trickier, as the corresponding table in UCSC has changed. I managed to build a compatible table for hg38 (same format as the hg19 one) using the following approach (using `python`, `bedtools`, `pandas` and `pyjanitor`):

#### Step 1: gather the data

```
# Get and merge the centromere intervals for both arms in a single value

mysql \
     --user=genome \
     --host=genome-mysql.cse.ucsc.edu \
     -A \ 
     -e "select * from hg38.cytoBandIdeo where gieStain = \"acen\"" | bedtools merge > hg38.centromeres

# Get the gap table

mysql --user=genome \
    --host=genome-mysql.cse.ucsc.edu \
    -A -e "select * from hg38.gap" > gap_hg38.temp

```

#### Step 2: build a table similar to the one for hg19

```python
#!/usr/bin/env python3

import argparse

import pandas as pd
import janitor # Mostly required for syntactic sugar

def main():
    
    parser = argparse.ArgumentParser()
    parser.add_argument("centromere", help="Centromere table")
    parser.add_argument("gap", help="Gap table")
    parser.add_argument("destination", help="Destination file name")
    
    options = parser.parse_args()
    gaps = pd.read_table(options.gap)
    # We create the headers because bedtools removed them
    centromere = pd.read_table(
        options.centromere, header=None, 
        names=["chrom", "chromStart", "chromEnd"])
    # Add a new column with "size" in 
    centromere = centromere.join_apply(
        lambda x: x.chromEnd - x.chromStart, "size"
    )

    # Build the final table, merging by chromosome, and fill in the NA values
    # Ix and bin are filled with arbitrary values
    final = (
        pd.concat([gaps, centromere])
        .fill_empty("type", "centromere")
        .fill_empty("bridge", "no")
        .fill_empty("n", "N")
        .fill_empty("ix", 0)
        .fill_empty("bin", 99999)
        .change_type("bin", int)
        .change_type("ix", int)
    )
    
    final.to_csv(options.destination, sep="\t", index=False)
    

if __name__ == "__main__":
    main()
```

Saving this as `create_gap_table.py` and executing it

```
python3 create_gap_table.py hg38.centromeres gap_hg38.temp gap_hg38
```

yields the data, which was then loaded directly in R and saved as `gap_hg38.rda`.

### Adding support to the code

To allow alternative genome builds, an additional `build` parameter was added to the functions, defaulting to `hg19` for compatibility reasons. The code tries to infer this from the `ExpData`'s `build` slot. Generic class definitions and methods should have been adjusted accordingly.

My limited testing has showed this code to be "working" in principle but I'd like more eyes over it.

### CODE REVIEW

**Comment by lbeltrame** [comment]
The hg38 gap table has no longer the centromere information, so this needs some more adjustments.

**Comment by lbeltrame** [comment]
I managed to build a compatible table for hg38 using the following approach (using `python`, `bedtools`, `pandas` and `pyjanitor`):

### Step 1: gather the data

```
# Get and merge the centromere intervals for both arms in a single value

mysql \
     --user=genome \
     --host=genome-mysql.cse.ucsc.edu \
     -A \ 
     -e "select * from hg38.cytoBandIdeo where gieStain = \"acen\"" | bedtools merge > hg38.centromeres

# Get the gap table

mysql --user=genome \
    --host=genome-mysql.cse.ucsc.edu \
    -A -e "select * from hg38.gap" > gap_hg38.temp

```

### Step 2: build a table similar to the one for hg19

```python
#!/usr/bin/env python3

import argparse

import pandas as pd
import janitor # Mostly required for syntactic sugar

def main():
    
    parser = argparse.ArgumentParser()
    parser.add_argument("centromere", help="Centromere table")
    parser.add_argument("gap", help="Gap table")
    parser.add_argument("destination", help="Destination file name")
    
    options = parser.parse_args()
    gaps = pd.read_table(options.gap)
    # We create the headers because bedtools removed them
    centromere = pd.read_table(
        options.centromere, header=None, 
        names=["chrom", "chromStart", "chromEnd"])
    # Add a new column with "size" in 
    centromere = centromere.join_apply(
        lambda x: x.chromEnd - x.chromStart, "size"
    )

    # Build the final table, merging by chromosome, and fill in the NA values
    # Ix and bin are filled with arbitrary values
    final = (
        pd.concat([gaps, centromere])
        .fill_empty("type", "centromere")
        .fill_empty("bridge", "no")
        .fill_empty("n", "N")
        .fill_empty("ix", 0)
        .fill_empty("bin", 99999)
        .change_type("bin", int)
        .change_type("ix", int)
    )
    
    final.to_csv(options.destination, sep="\t", index=False)
    

if __name__ == "__main__":
    main()
```

```
python3 create_gap_table.py hg38.centromeres gap_hg38.temp gap_hg38
```

I'll be testing to see if it works properly like this.

**Comment by lbeltrame** [comment]
Lo and behold, it works with some in-house data:

```r
library(CINSignatureQuantification)
library(tidyverse)
seg <- read_tsv("segments-for-signatures.tsv")
res <- quantifyCNSignatures(seg, method="drews", cores=6, build="hg38")

head(getSampleByComponent(res))
```

This yields (partial output):

```
        segsize1     segsize2     segsize3   segsize4   segsize5    segsize6     segsize7     segsize8
1    2.664816e-11 3.256260e-01 1.9986032481  5.2204443  4.4338310  7.83030446  8.854809085 9.962163e+00
10   1.178834e-48 4.223047e-08 0.4766949449  2.1321572  4.1204556  4.02627713  5.656506065 5.771695e+00
```

**Comment by Phil9S** [comment]
Thanks for your patience and many thanks for putting this together, it is very thorough. I'll make sure it all installs and runs as I'd expect to but I think it will be absolutely fine. It looks very similar to a local implementation I have of hg38 support but if your version is robust and works I will just merge your pull request instead when I've had time to review properly.

**Comment by lbeltrame** [comment]
Thanks. Feel free to point out issues if you find them, and I'll fix them. I've been running some de novo signature extractions with the components generated with this PR and from a cursory glance they look fine.

**Pull request merged**
